apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: pod-backend
spec:
  type: NodePort
  selector:
    app: pod-backend
  ports:
  - protocol: TCP
    port: 80 # Port on the service
    targetPort: 8080 # Port on the pod (container)
    nodePort: 30080 # Port exposed on the node
